name: /Users/groot/Documents/T4T5_scAnalysis/clustering_analysis-new/renv/python/condaenvs/renv-python
channels:
  - defaults
  - conda-forge
dependencies:
  - arpack=3.9.1=nompi_hf81eadf_101
  - bzip2=1.0.8=hfdf4475_7
  - ca-certificates=2024.8.30=h8857fd0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - glpk=5.0=h3cb5acd_0
  - gmp=6.3.0=hf036a51_2
  - icu=75.1=h120a0e1_0
  - igraph=0.10.13=hde4452d_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - leidenalg=0.9.1=py39h7a8716b_0
  - libblas=3.9.0=22_osx64_openblas
  - libcblas=3.9.0=22_osx64_openblas
  - libcxx=19.1.0=hf95d169_0
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - libhwloc=2.11.1=default_h456cccd_1000
  - libiconv=1.17=hd75f5a5_2
  - liblapack=3.9.0=22_osx64_openblas
  - libllvm14=14.0.6=hc8e404f_4
  - libopenblas=0.3.27=openmp_h8869122_1
  - libsqlite=3.46.1=h4b8f8c9_0
  - libxml2=2.12.7=heaf3512_4
  - libzlib=1.3.1=h87427d6_1
  - llvm-openmp=18.1.8=h15ab845_1
  - llvmlite=0.43.0=py39h164c851_1
  - ncurses=6.5=hf036a51_1
  - numba=0.60.0=py39h90d9702_0
  - numpy=1.26.4=py39h28c39a1_0
  - openssl=3.3.2=hd23fc13_0
  - pandas=2.2.3=py39h88a5ddd_1
  - pip=24.2=pyh8b19718_1
  - pynndescent=0.5.13=pyhff2d567_0
  - python=3.9.20=hf24efe3_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-igraph=0.11.6=py39h29643ac_2
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.9=5_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - readline=8.2=h9e318b2_1
  - scikit-learn=1.5.2=py39h771d6a6_1
  - scipy=1.13.1=py39h038d4f4_0
  - setuptools=75.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.46.1=he26b093_0
  - tbb=2021.13.0=h37c8870_0
  - texttable=1.7.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h1abcd95_1
  - tqdm=4.66.5=pyhd8ed1ab_0
  - tzdata=2024a=h8827d51_1
  - umap-learn=0.5.3=py39h6e9494a_1
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h775f41a_0
prefix: /Users/groot/Documents/T4T5_scAnalysis/clustering_analysis-new/renv/python/condaenvs/renv-python
