channels:
  - conda-forge
  - defaults
dependencies:
  - igraph=0.10.2
  - leidenalg=0.9.1
  - pandas=2.1.0
  - pip=22.3.1
  - python=3.9.13
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - umap-learn=0.5.3
